In [151]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
from astropy.coordinates import SkyCoord


masers = pd.read_csv('/Volumes/GalagaResearch/Developer/masers/W51/W51-Masers-and-Starforming-Regions/notebooks/w51_irs2_ammonia_maser_spectral_spatial_fits.csv')
sources = pd.read_csv('/Volumes/GalagaResearch/Developer/masers/W51/W51-Masers-and-Starforming-Regions/notebooks/FK5_ICRS_offsets/offset_sources.csv')

masers

,line_sp,x_pix,y_pix,S,freq0,linewidth,S_err,freq0_err,linewidth_err,vlsr_ms,...,y_mean_pix,ra_hms,dec_dms,ra_hms_error,dec_dms_error,SkyCoord_pix,frame,header,j_transition,k_transition
0,"(5,3)",638,356,0.458479,21.281264,0.000018,0.005651,2.513016e-07,2.510602e-07,56490.507669,...,355.918004,19:23:39.8141,14:31:04.8181,0:00:00.00021,0:00:00.00292,"(array(637.67009513), array(355.91800412))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,5,3
1,"(5,3)",630,358,0.078289,21.281402,0.000023,0.005496,1.853438e-06,1.853393e-06,54555.616440,...,358.026538,19:23:39.8213,14:31:04.8476,0:00:00.00036,0:00:00.00497,"(array(630.25191071), array(358.02653767))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,5,3
2,"(6,2)",637,359,0.039023,18.881276,0.000034,0.002095,2.086243e-06,2.086225e-06,54276.077085,...,358.605141,19:23:39.8153,14:31:04.8557,0:00:00.00049,0:00:00.00731,"(array(636.50010085), array(358.60514094))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,6,2
3,"(6,3)",638,356,0.860660,19.753856,0.000017,0.003791,8.623100e-08,8.625913e-08,55864.063709,...,356.090290,19:23:39.8140,14:31:04.8205,0:00:00.00022,0:00:00.00288,"(array(637.76966703), array(356.09029035))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,6,3
4,"(6,3)",630,358,0.148111,19.753989,0.000017,0.004385,5.737189e-07,5.736626e-07,53843.513804,...,358.075393,19:23:39.8216,14:31:04.8483,0:00:00.00029,0:00:00.00387,"(array(629.92829888), array(358.07539318))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,6,3
5,"(7,4)",637,358,0.046770,19.215017,0.000026,0.003130,1.992742e-06,1.992711e-06,53783.987401,...,357.949429,19:23:39.8148,14:31:04.8465,0:00:00.00036,0:00:00.00489,"(array(636.92328862), array(357.94942883))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,4
6,"(7,5)",637,358,2.458160,20.801060,0.000028,0.021771,2.900901e-07,2.900858e-07,54321.932476,...,358.443144,19:23:39.8148,14:31:04.8535,0:00:00.00017,0:00:00.00211,"(array(636.99796567), array(358.4431435))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,5
7,"(7,6)",344,415,0.363998,22.921291,0.000032,0.005829,6.262045e-07,6.543783e-07,47721.129438,...,415.232386,19:23:40.0975,14:31:05.6485,0:00:00.00027,0:00:00.00336,"(array(343.73118244), array(415.23238639))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,6
8,"(7,6)",344,415,0.253679,22.921153,0.000040,0.005314,1.018450e-06,1.187858e-06,49521.673335,...,415.209244,19:23:40.0978,14:31:05.6482,0:00:00.00032,0:00:00.00391,"(array(343.40757117), array(415.20924353))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,6
9,"(7,6)",344,415,0.234593,22.921006,0.000032,0.005775,9.490850e-07,9.862761e-07,51439.704535,...,415.268386,19:23:40.0979,14:31:05.6490,0:00:00.00036,0:00:00.00542,"(array(343.382678), array(415.26838639))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,6
10,"(7,7)",344,415,0.041862,25.710927,0.000063,0.004853,9.174856e-06,1.017921e-05,49601.517691,...,414.838958,19:23:40.0976,14:31:05.6430,0:00:00.00046,0:00:00.00634,"(array(343.63160975), array(414.83895781))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,7
11,"(7,7)",344,415,0.552206,25.711087,0.000030,0.007140,5.529165e-07,5.878157e-07,47739.164066,...,415.191244,19:23:40.0975,14:31:05.6479,0:00:00.00008,0:00:00.00114,"(array(343.78096879), array(415.19124353))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,7
12,"(7,7)",344,415,0.227686,25.711217,0.000051,0.005420,1.704628e-06,1.880242e-06,46228.968174,...,415.191244,19:23:40.0975,14:31:05.6479,0:00:00.00012,0:00:00.00165,"(array(343.78096879), array(415.19124353))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,7
13,"(8,5)",637,358,0.112321,18.805110,0.000020,0.003232,6.639265e-07,6.639031e-07,54148.877121,...,358.021428,19:23:39.8149,14:31:04.8476,0:00:00.00025,0:00:00.00314,"(array(636.84860865), array(358.02142844))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,8,5
14,"(9,8)",637,358,0.175800,23.653175,0.000020,0.004996,6.718934e-07,6.718619e-07,54440.927757,...,358.057430,19:23:39.8146,14:31:04.8481,0:00:00.00025,0:00:00.00338,"(array(637.19711326), array(358.05743024))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,9,8
15,"(11,9)",407,413,0.083396,21.066420,0.000019,0.004982,1.329404e-06,1.329248e-06,61451.323664,...,413.108421,19:23:40.0370,14:31:05.6188,0:00:00.00035,0:00:00.00477,"(array(406.51177121), array(413.1084213))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,11,9
16,"(11,9)",365,397,0.037612,21.066456,0.000023,0.004565,3.247970e-06,3.247897e-06,60939.201999,...,396.908391,19:23:40.0765,14:31:05.3920,0:00:00.00068,0:00:00.00936,"(array(365.51271734), array(396.90839065))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,11,9
17,"(11,9)",344,415,0.416496,21.067399,0.000029,0.005975,4.855923e-07,4.855854e-07,47518.035951,...,415.160386,19:23:40.0974,14:31:05.6475,0:00:00.00019,0:00:00.00258,"(array(343.83075514), array(415.16038639))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,11,9

In [5]:
masers.columns

Index(['line_sp', 'x_pix', 'y_pix', 'S', 'freq0', 'linewidth', 'S_err',
       'freq0_err', 'linewidth_err', 'vlsr_ms', 'vlsr_kms', 'vlsr_ms_err',
       'vlsr_kms_err', 'linewidth_ms', 'linewidth_kms', 'linewidth_ms_err',
       'linewidth_kms_err', 'fwhm_kms', 'fwhm_kms_err', 'source', 'color',
       'line', 'spw', 'channel', 'x_pix.1', 'y_pix.1', 'amplitude',
       'amplitude_error', 'x_mean', 'x_mean_error', 'y_mean', 'y_mean_error',
       'x_mean_sky', 'y_mean_sky', 'x_mean_pix', 'y_mean_pix', 'ra_hms',
       'dec_dms', 'ra_hms_error', 'dec_dms_error', 'SkyCoord_pix', 'frame',
       'header', 'j_transition', 'k_transition'],
      dtype='object')

In [20]:
masers[(masers['source'] == 'CA3')]

,line_sp,x_pix,y_pix,S,freq0,linewidth,S_err,freq0_err,linewidth_err,vlsr_ms,...,y_mean_pix,ra_hms,dec_dms,ra_hms_error,dec_dms_error,SkyCoord_pix,frame,header,j_transition,k_transition
7,"(7,6)",344,415,0.363998,22.921291,0.000032,0.005829,6.262045e-07,6.543783e-07,47721.129438,...,415.232386,19:23:40.0975,14:31:05.6485,0:00:00.00027,0:00:00.00336,"(array(343.73118244), array(415.23238639))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,6
8,"(7,6)",344,415,0.253679,22.921153,0.000040,0.005314,1.018450e-06,1.187858e-06,49521.673335,...,415.209244,19:23:40.0978,14:31:05.6482,0:00:00.00032,0:00:00.00391,"(array(343.40757117), array(415.20924353))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,6
9,"(7,6)",344,415,0.234593,22.921006,0.000032,0.005775,9.490850e-07,9.862761e-07,51439.704535,...,415.268386,19:23:40.0979,14:31:05.6490,0:00:00.00036,0:00:00.00542,"(array(343.382678), array(415.26838639))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,6
10,"(7,7)",344,415,0.041862,25.710927,0.000063,0.004853,9.174856e-06,1.017921e-05,49601.517691,...,414.838958,19:23:40.0976,14:31:05.6430,0:00:00.00046,0:00:00.00634,"(array(343.63160975), array(414.83895781))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,7
11,"(7,7)",344,415,0.552206,25.711087,0.000030,0.007140,5.529165e-07,5.878157e-07,47739.164066,...,415.191244,19:23:40.0975,14:31:05.6479,0:00:00.00008,0:00:00.00114,"(array(343.78096879), array(415.19124353))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,7
12,"(7,7)",344,415,0.227686,25.711217,0.000051,0.005420,1.704628e-06,1.880242e-06,46228.968174,...,415.191244,19:23:40.0975,14:31:05.6479,0:00:00.00012,0:00:00.00165,"(array(343.78096879), array(415.19124353))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,7,7
17,"(11,9)",344,415,0.416496,21.067399,0.000029,0.005975,4.855923e-07,4.855854e-07,47518.035951,...,415.160386,19:23:40.0974,14:31:05.6475,0:00:00.00019,0:00:00.00258,"(array(343.83075514), array(415.16038639))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,11,9

In [24]:
ra_ca3_masers = masers[(masers['source'] == 'CA3')]['x_mean'].values

In [ ]:
dec_ca3_masers = masers[(masers['source'] == 'CA3')]['y_mean'].values

In [73]:
coords_ca3 = SkyCoord(ra_ca3_masers, dec_ca3_masers, unit=(u.deg, u.deg), frame='icrs')

In [114]:
ra_d2_masers = masers[(masers['source'] == 'd2')]['x_mean'].values
dec_d2_masers = masers[(masers['source'] == 'd2')]['y_mean'].values
coords_d2 = SkyCoord(ra_d2_masers, dec_d2_masers, unit=(u.deg, u.deg), frame='icrs')

ra_w51north_masers = masers[(masers['source'] == 'W51North')]['x_mean'].values
dec_w51north_masers = masers[(masers['source'] == 'W51North')]['y_mean'].values
coords_w51north = SkyCoord(ra_w51north_masers, dec_w51north_masers, unit=(u.deg, u.deg), frame='icrs')

In [141]:
masers[(masers['source'] == 'W51North')]

,line_sp,x_pix,y_pix,S,freq0,linewidth,S_err,freq0_err,linewidth_err,vlsr_ms,...,y_mean_pix,ra_hms,dec_dms,ra_hms_error,dec_dms_error,SkyCoord_pix,frame,header,j_transition,k_transition
15,"(11,9)",407,413,0.083396,21.066420,0.000019,0.004982,0.000001,0.000001,61451.323664,...,413.108421,19:23:40.0370,14:31:05.6188,0:00:00.00035,0:00:00.00477,"(array(406.51177121), array(413.1084213))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,11,9
16,"(11,9)",365,397,0.037612,21.066456,0.000023,0.004565,0.000003,0.000003,60939.201999,...,396.908391,19:23:40.0765,14:31:05.3920,0:00:00.00068,0:00:00.00936,"(array(365.51271734), array(396.90839065))",icrs,WCS Keywords\n\nNumber of WCS axes: 2\nCTYPE :...,11,9

0           d2
1           d2
2           d2
3           d2
4           d2
5           d2
6           d2
7          CA3
8          CA3
9          CA3
10         CA3
11         CA3
12         CA3
13          d2
14          d2
15    W51North
16    W51North
17         CA3
Name: source, dtype: object

In [ ]:
# from Kband_separation.ipynb. 

ra_ca3_Kband_source = 290.9170697
dec_ca3_Kband_source = 14.51823865

ca3_Kband_source = SkyCoord(ra_ca3_Kband_source, dec_ca3_Kband_source, unit=(u.deg, u.deg), frame='icrs')

In [136]:
distances = []
separations = []
for i in zip(ra_ca3_masers, dec_ca3_masers):
    # print(ra_ca3_Kband_source - i[0])
    # print(dec_ca3_Kband_source - i[1])

    distance = np.sqrt((ra_ca3_Kband_source - i[0])**2 + (dec_ca3_Kband_source - i[1])**2)
    print(distance * u.deg.to(u.arcsec))
    distances.append(distance * u.deg.to(u.arcsec))

distance_from_ca3 = np.mean(distances) * u.arcsec

for i in range(len(distances)):
    coords_ca3[i].separation(ca3_Kband_source).to(u.arcsec)
    separation = coords_ca3[i].separation(ca3_Kband_source).to(u.arcsec)
    separations.append(separation.value)

separations = np.array(separations)
np.max(separations), np.max(separations) * 5128

0.01593482978619699
0.01984955257455814
0.01971344346592093
0.020917332099302823
0.015808099737830764
0.015808099737830764
0.01562702728631751

(np.float64(0.020649085995536755), np.float64(105.88851298511248))

In [61]:
distance_from_ca3

In [64]:
distance = 5128 * u.pc

(distance_from_ca3 * distance).value

np.float64(90.5885995256926)

In [135]:
# from Kband_separation.ipynb. 

ra_d2_Kband_source = 290.91590672
dec_d2_Kband_source = 14.51800645
d2_Kband_source = SkyCoord(ra_d2_Kband_source, dec_d2_Kband_source, unit=(u.deg, u.deg), frame='icrs')

separations = []

for i in range(len(distances)):
    coords_d2[i].separation(d2_Kband_source).to(u.arcsec)
    separation = coords_d2[i].separation(d2_Kband_source).to(u.arcsec)
    separations.append(separation.value)

separations = np.array(separations)
np.max(separations), np.max(separations) * 5128

(np.float64(0.06299507169211854), np.float64(323.0387276371839))

In [109]:
coords_w51north

<SkyCoord (ICRS): (ra, dec) in deg
    []>

In [148]:
ra_w51north_Kband_source = 290.91687133
dec_w51north_Kband_source = 14.51818835
w51north_Kband_source = SkyCoord(ra_w51north_Kband_source, dec_w51north_Kband_source, unit=(u.deg, u.deg), frame='icrs')

separations = []
pa = []

for i in range(0,2):
    coords_w51north[i].separation(w51north_Kband_source).to(u.arcsec)
    separation = coords_w51north[i].separation(w51north_Kband_source).to(u.arcsec)
    separations.append(separation.value)

    position_angle = coords_w51north[i].position_angle(w51north_Kband_source).to(u.deg)
    pa.append(position_angle.value)



separations = np.array(separations)
np.max(separations), np.max(separations) * 5128

(np.float64(0.40709169105182225), np.float64(2087.5661917137445))

In [150]:
separations[0], separations[0] * 5128

(np.float64(0.22542008343968972), np.float64(1155.9541878787288))

In [138]:
np.mean(separations)

np.float64(0.316255887245756)

In [142]:
pa

[np.float64(128.62894792937436), np.float64(282.20684431772145)]

AttributeError: 'numpy.float64' object has no attribute 'wrap_angle' and no __dict__ for setting new attributes